#Q1.Calculate the total revenue generated by two product categories in a store
#Solution=>>

import numpy as np

#Define the revenue array for Category 1 (sales figures for different periods)
category1_revenue = np.array([500, 600, 700, 550])

#Define the revenue array for Category 2 (sales figures for the same periods as Category 1)
category2_revenue = np.array([450, 700, 800, 600])

#Calculate total revenue by adding revenue from both categories element-wise
#This gives the combined revenue for each period
total_revenue = category1_revenue + category2_revenue

#Print the calculated total revenue for each period
print("Total revenue generated by two product categories in a store is :", total_revenue)

"""ANS=>>

 Total revenue generated by two product categories in a store is : [ 950 1300 1500 1150]

"""


